### ISSUE TITLE
xy_left and xy_right explanation in Semantic Rasterizer.

### ISSUE THREAD

**Issue by oljike** [lyft/l5kit#199]
HI! Could You please the meaning and difference between xy_left and xy_right points in Semantic Rasterizer. When I try to rasterize only xy_lefts or xy_rights, there's a difference in visualization, but I don't see logical difference.

only xy_left
![left](https://user-images.githubusercontent.com/71707643/99661344-e5421280-2a8d-11eb-8e9d-b4e838edaa1e.png)

only xy_right
![right](https://user-images.githubusercontent.com/71707643/99661380-f2f79800-2a8d-11eb-8dc2-e5b7da47d589.png)

both 
![both](https://user-images.githubusercontent.com/71707643/99661690-67323b80-2a8e-11eb-8886-fd88664bd842.png)

**Comment by lucabergamini** [comment]
Hi @oljike,

Each lane has a left and right boundary (we're adding centrelane but it is still not there). It can happen that two adjacent lanes share coordinates from one of the boundaries. This means left from one could overlap perfectly with right from the other (that's why you're seeing the "same" line in both). Other times , it seems like only one is there instead (I'm not responsible for the map file creation, so I don't have many more details on this, sorry)

Hope this answer to your question :)  I'll close but I'll keep on eye on this in case you have any more related questions
