### ISSUE TITLE
Number of Agents from get_frame_indices does not match image

### ISSUE THREAD

**Issue by LukasWFurtner** [lyft/l5kit#220]
Hi,
I have a question regarding the get_frame_indices() method that is related to #107 and #186.
I want to access the Agents in a given frame of the Egodataset via the Agentdataset. However, the number of agents from agent_dt.get_frame_indices(frame) does not seem to fit the number of agents one can see in the frame. For example, the frame 232 of the sample.zarr shows two agents, but agent_dt.get_frame_indices(232) returns: array([], dtype=int64).

![Github_issue](https://user-images.githubusercontent.com/63885140/103521697-7a03a280-4e79-11eb-9a9d-0d5b10472480.png)

What am I doing wrong?

Best regards
Lukas

```
import os
import sys 
import matplotlib.pyplot as plt

from l5kit.configs import load_config_data
from l5kit.data import LocalDataManager, ChunkedDataset, get_agents_slice_from_frames, get_frames_slice_from_scenes, get_tl_faces_slice_from_frames
from l5kit.rasterization import build_rasterizer
from l5kit.dataset import AgentDataset, EgoDataset

os.environ["L5KIT_DATA_FOLDER"] = "" # PATH_TO_DATA
cfg = load_config_data("")  # PATH_TO_CONFIG
dm = LocalDataManager()
dataset_path = dm.require(cfg["val_data_loader"]["key"])
zarr_dataset = ChunkedDataset(dataset_path)
zarr_dataset.open()
rast = build_rasterizer(cfg, dm)
agent_dt = AgentDataset(cfg, zarr_dataset, rast)
ego_dt = EgoDataset(cfg, zarr_dataset, rast)

im = ego_dt[232]["image"].transpose(1, 2, 0)
im = ego_dt.rasterizer.to_rgb(im)
plt.imshow(im[::-1])

agent_dt.get_frame_indices(232)
```

**Comment by lucabergamini** [comment]
Hi @LukasWFurtner 



> What am I doing wrong?

Nothing :) However the agent dataset performs filtering over agents to get the "reliable" ones. This means that even if you have two agents in that frames, those may not be reliable because:
- they disappear in the next one or they were not there in the previous ones;
- they change extents or yaws abruptly

The raster doesn't use this info, so it just renders everything which is above the 0.5 threshold from the perception.

I'm positive this is not a bug, but I'll check it nonetheless just to be extra sure :)

**Comment by LukasWFurtner** [comment]
Thank you for the fast answer :) and sorry for my late reply.
