### ISSUE TITLE
Clarification about distance_ref_trajectory

### ISSUE THREAD

**Issue by FrancescoMandru** [lyft/l5kit#308]
In your code it is written than differently from L2 displacement:  

> This metric will compute the distance from the predicted centroid to the closest waypoint in the reference trajectory.

What do you mean by the predicted centroid? Do you compute the center point of the trajectory and then you find the closest point to the ground truth? If so, why do you consider such metric?

Thank you!

**Comment by lucabergamini** [comment]
This metric does not depend on time (differently from L2).

Imagine the following situation:
- your simulated ego is 10m ahead of replayed at time step T;
- the simulated ego is still on the reference trajectory (built from all observations of replayed ego in that scene), so the distance to the closest point is 10cm

L2 will trigger (because at T you're 10m off).
Distance to ref won't because you're still on the ref trajectory

**Comment by FrancescoMandru** [comment]
Thank you. So a common case where the ref trajetcory trigger is when there are lateral deviations with respect to the annotated trajectory for example?

**Comment by lucabergamini** [comment]
correct!

**Comment by FrancescoMandru** [comment]
Last question, in Open Loop evaluation you evaluate the ADE. Is this metric similar to the L2 displacement computed in Closed Loop?
