### ISSUE TITLE
Request For More Detailed Rasterized Dataset Documentation

### ISSUE THREAD

**Issue by billythedummy** [lyft/l5kit#98]
Couple of questions/details about the datasets returned by `EgoDataset()` and `AgentDataset()` that I wasn't able to find on the l5kit documentation or lyft level5 prediction website:

- **Units**: What units are `target_positions`, `centroid`, `extent`, `target_yaws` and `yaw` in? I'm guessing meters and radians respectively.
- **Absolute or relative?**: From the example notebooks, it seems like `target_positions` are displacements relative to the initial `centroid` point at the start of a sequence. Is this also the case for `target_yaws` and `yaw`, where we can calculate the absolute yaw heading at time step `i` in a sequence by taking `yaw + target_yaws[i]`?
- **target_availabilities**:  This field has a dimension of (batch, future_num_frames, 3). From its name I'm guessing it's a binary mask, but what does the last dimension correspond to? x, y, yaw respectively? Additionally, what does it mean for target_availability=0, does this correspond to an instance of the sensors' failure to calculate this dimension of the agent at this point in time in real-life?

I think it would be helpful to document details such as the ones above (and others such as `EgoDataset()` having -1 for `track_id`) somewhere. Thank you!

**Comment by lucabergamini** [comment]
Hi @billythedummy. 

> I think it would be helpful to document details such as the ones above

I'm working on adding some doc for the different reference systems #66 , but it's not my current higher priority sadly :( 



> * **Units**: What units are `target_positions`, `centroid`, `extent`, `target_yaws` and `yaw` in? I'm guessing meters and radians respectively.

yes, meters and radians



> * **Absolute or relative?**: From the example notebooks, it seems like `target_positions` are displacements relative to the initial `centroid` point at the start of a sequence. Is this also the case for `target_yaws` and `yaw`, where we can calculate the absolute yaw heading at time step `i` in a sequence by taking `yaw + target_yaws[i]`?

Yes [they are both relative](https://github.com/lyft/l5kit/blob/e30740346d7f9092cd6c5bedec877fe6332d413c/l5kit/l5kit/sampling/agent_sampling.py#L201)



> * **target_availabilities**:  This field has a dimension of (batch, future_num_frames, 3). From its name I'm guessing it's a binary mask, but what does the last dimension correspond to? x, y, yaw respectively? Additionally, what does it mean for target_availability=0, does this correspond to an instance of the sensors' failure to calculate this dimension of the agent at this point in time in real-life?

DISCLAIMER: target_availabilities is going through a refactoring atm and will likely change shape (last axes removed).

Yes, right now they three boolean values correspond to `x,y,yaw`. They can be set to 0 under two conditions:
- when you're working with the EgoDataset, even though the pose is always reliable (because acquired using internal sensors in the car) you will have 0 avail at the end of a scene
- when working with the AgentDataset, agents are not that reliable (sensors can fail to pick them up) or they may disappear naturally out of the AV perception range
Those are the two reasons why we need to model availability. Those values can be used for example in the loss to discard useless data (invalid data are set to 0 in the dataset)

**Comment by yousef-xailient** [comment]
Hi @lucabergamini,

What are the velocity units?
